### ISSUE TITLE
notification crashes the app

### ISSUE THREAD

**Issue by geekgonecrazy** [flathub/chat.rocket.RocketChat#121]
_Originally posted by @bbhtt in https://github.com/flathub/chat.rocket.RocketChat/issues/118#issuecomment-1743093848_

>>>
Can you get a backtrace and open an issue here, please? Follow https://www.figuiere.net/technotes/notes/tn001/

You'll need to `flatpak install` the following from flathub:

```
org.freedesktop.Sdk//23.08
org.freedesktop.Sdk.Debug//23.08
chat.rocket.RocketChat.Debug
org.electronjs.Electron2.BaseApp.Debug//23.08
```

The first two will be around 3-4 GB so have free space.

Then from `coredumpctl list` get the PID of the crash, run `flatpak-coredumpctl -m PID chat.rocket.RocketChat`, then enter `bt` at the `(gdb)` prompt.
<<<

Output is:
```
This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /app/bin/../lib/libzypak-preload-host.so
Downloading separate debug info for /app/bin/../lib/libzypak-preload-host-spawn-strategy.so
Downloading separate debug info for /usr/lib/x86_64-linux-gnu/libcups.so.2
Downloading separate debug info for /usr/lib/x86_64-linux-gnu/GL/default/lib/libgbm.so.1
Downloading separate debug info for /usr/lib/x86_64-linux-gnu/libnss_resolve.so.2
Downloading separate debug info for /app/lib/libnotify.so.4
Downloading separate debug info for system-supplied DSO at 0x7ffe01163000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/app/Rocket.Chat/rocketchat-desktop --ozone-platform-hint=auto'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.

warning: Section `.reg-xstate/2' in core file too small.
#0  0x000055be57adc5aa in ?? ()
[Current thread is 1 (Thread 0x7f254e1b1640 (LWP 2))]
(gdb) bt
#0  0x000055be57adc5aa in  ()
#1  0x000055be57adc530 in  ()
#2  0x00007ffe010fa110 in  ()
#3  0x000015d804396040 in  ()
#4  0x000015d802b1c280 in  ()
#5  0x00007ffe010fa100 in  ()
#6  0x000055be57aded14 in  ()
#7  0x000015d804396040 in  ()
#8  0x00007ffe010fa1e0 in  ()
#9  0x000015d804396040 in  ()
#10 0x00007ffe010fa110 in  ()
#11 0x000055be57adeb80 in  ()
#12 0x00000e4200b517b9 in  ()
#13 0x00007ffe010fa200 in  ()
#14 0x0000000000000000 in  ()
```

**Comment by bbhtt** [comment]
This has nothing unfortunately.


The libnotify issue I mentioned was fixed and update pushed to the Electron baseapp. Give, 4-5 hours for the baseapp update to be published, then rebuild rocketchat against it via https://buildbot.flathub.org/. 

Then see if it fixes any issues.

**Comment by andrevmatos** [comment]
I'm trying to rebuild, but being greeted with this error:
flathub/org.flatpak.Builder#185
https://buildbot.flathub.org/#/builders/7/builds/8887

**Comment by bbhtt** [comment]
Ah yea :( 

You need to wait until the fix for that gets deployed on the server (probably within the next working day or two)

**Comment by bbhtt** [comment]
I triggered a rebuild https://buildbot.flathub.org/#/builders/6/builds/72150 wait 4-5 hours for it to be published
