### ISSUE TITLE
Wont start properly

### ISSUE THREAD

**Issue by hansvurst-foss** [flathub/chat.rocket.RocketChat#54]
### Steps to reproduce
1. Start flatpak from desktop environment or cli
2. App starts but gets stuck very soon

### Expected behaviour
App should start and open the main window.

### Actual behaviour
App gets stuck with sleeping processes.

### Flatpak info
```
$ uname -a
Linux ### 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
$ flatpak --version
Flatpak 1.2.5
```

### RocketChat info
```
$ flatpak info chat.rocket.RocketChat
Rocket.Chat - Open Source Team Communication

          ID: chat.rocket.RocketChat
         Ref: app/chat.rocket.RocketChat/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.2.2
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 207,4 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08
```

<details>
<summary>Log after starting on CLI</summary>

```
$ flatpak run chat.rocket.RocketChat
[3 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property “supports”
[3 zypak-helper] Portal v4 is not available
[bugsnag] Loaded!
Gtk-Message: 11:23:11.346: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:23:11.346: Failed to load module "canberra-gtk-module"
[bugsnag] Unhandled rejection…
Error: cannot handle null server URLs
    at ensureUrlFormat (/app/Rocket.Chat/resources/app.asar/app/main.js:243:11)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:314:93
    at Array.map (<anonymous>)
    at servers (/app/Rocket.Chat/resources/app.asar/app/main.js:314:28)
    at combination (/app/Rocket.Chat/resources/app.asar/node_modules/redux/lib/redux.js:536:29)
    at dispatch (/app/Rocket.Chat/resources/app.asar/node_modules/redux/lib/redux.js:296:22)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:86:16
    at Object.dispatch (/app/Rocket.Chat/resources/app.asar/app/main.js:645:12)
    at dispatch (/app/Rocket.Chat/resources/app.asar/app/main.js:652:16)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:1191:5
[bugsnag] Unhandled rejection…
Error: cannot handle null server URLs
    at ensureUrlFormat (/app/Rocket.Chat/resources/app.asar/app/rootWindow-d7e0dc72.js:3401:11)
    at /app/Rocket.Chat/resources/app.asar/app/rootWindow-d7e0dc72.js:3472:93
    at Array.map (<anonymous>)
    at servers (/app/Rocket.Chat/resources/app.asar/app/rootWindow-d7e0dc72.js:3472:28)
    at combination (/app/Rocket.Chat/resources/app.asar/node_modules/redux/lib/redux.js:536:29)
    at dispatch (/app/Rocket.Chat/resources/app.asar/node_modules/redux/lib/redux.js:296:22)
    at /app/Rocket.Chat/resources/app.asar/app/rootWindow-d7e0dc72.js:3803:12
    at /app/Rocket.Chat/resources/app.asar/app/rootWindow-d7e0dc72.js:3246:20
    at Object.dispatch (/app/Rocket.Chat/resources/app.asar/node_modules/redux/lib/redux.js:667:28)
    at /app/Rocket.Chat/resources/app.asar/app/rootWindow-d7e0dc72.js:3242:13
```
<details>

**Comment by andrevmatos** [comment]
This seems to be an issue with your server. I can't reproduce it locally. Please, try clearing your local data (`~/.var/app/chat.rocket.RocketChat`) and relogging.
